spring:
  datasource:
    url: jdbc:mysql://localhost:3306/laia_trailcat
    username: ironhacker
    password: 1r0nh4ck3r
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true #show commands on terminal that are being executed
  #generate-ddl: true # => como el update de abajo
  hibernate:
    ddl-auto: update # update => para simplemente trabajar sin hacer un drop de la tabla
server:
  port: 8090
